language: node_js

node_js:
  - '8.9'

sudo: required

cache:
  directories:
    - node_modules

addons:
  chrome: stable

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm config set spin false"

before_script:
  - "npm install"

script: "npm run smoke"