# This is a basic workflow to help you get started with Actions

name: WebdriverIO smoke

on: [push]
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install
        run: npm install
      - name: WDIO run
        run: npm run test-headless
        
  
